plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
}

dependencies {

    // JUnit 5
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // REST Assured
    testImplementation 'io.rest-assured:rest-assured:5.5.5'
    testImplementation 'io.rest-assured:json-path:5.5.5'
    testImplementation 'io.rest-assured:xml-path:5.5.5'

    // Jackson
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.20.0'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.42'
    annotationProcessor 'org.projectlombok:lombok:1.18.42'

    testCompileOnly 'org.projectlombok:lombok:1.18.42'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.42'

    // AssertJ
    testImplementation 'org.assertj:assertj-core:3.27.4'

    // Faker для тестовых данных
    testImplementation 'net.datafaker:datafaker:2.4.3'

    // Source: https://mvnrepository.com/artifact/com.codeborne/selenide
    implementation 'com.codeborne:selenide:7.18.0'
}

test {
    useJUnitPlatform()
}